configLeaderElection:
  leaseDuration: 60s
  renewDeadline: 40s
  retryPeriod: 10s
configLogging:
  loglevelController: info
  loglevelWebhook: info
  zapLoggerConfig: |
    {
      "level": "info",
      "development": false,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
controller:
  ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
    - name: probes
      port: 8080
      targetPort: 0
  replicas: 1
  tektonPipelinesController:
    image:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
      tag: v0.37.2
    kubeconfigWriterImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter
      tag: v0.37.2
    gitImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init
      tag: v0.37.2
    entrypointImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint
      tag: v0.37.2
    nopImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop
      tag: v0.37.2
    imagedigestExporterImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter
      tag: v0.37.2
    prImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init
      tag: v0.37.2
    workingdirinitImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit
      tag: v0.37.2
    gsutilImage:
      repository: gcr.io/google.com/cloudsdktool/cloud-sdk
      tag:
      digest: sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f
    shellImage:
      repository: ghcr.io/distroless/busybox
      tag:
      digest: sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
    shellImageWin:
      repository: mcr.microsoft.com/powershell:nanoserver
      tag:
      digest: sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
  type: ClusterIP
featureFlags:
  disableAffinityAssistant: "false"
  disableCredsInit: "false"
  enableApiFields: stable
  enableCustomTasks: "false"
  enableTektonOciBundles: "false"
  requireGitSshSecretKnownHosts: "false"
  runningInEnvironmentWithInjectedSidecars: "true"
  sendCloudeventsForRuns: "false"
kubernetesClusterDomain: cluster.local
pipelinesInfo:
  version: v0.37.2
webhook:
  ports:
    - name: http-metrics
      port: 9090
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
    - name: https-webhook
      port: 443
      targetPort: 8443
    - name: probes
      port: 8080
      targetPort: 0
  replicas: 1
  type: ClusterIP
  webhook:
    image:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
      tag: v0.37.2
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
