configDefaults:
configLeaderElection:
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
configLogging:
  loglevelController: info
  loglevelWebhook: info
  zapLoggerConfig: |
    {
      "level": "info",
      "development": false,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
configObservability:
controller:
  ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
    - name: probes
      port: 8080
      targetPort: 0
  replicas: 1
  tektonPipelinesController:
    image:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
      tag: v0.30.0
      digest: sha256:ecb7567431d9c2b899be7b04cd5a72722655e36fd58f69ed695e469daab9009b
    kubeconfigWriterImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter
      tag: v0.30.0
      digest: sha256:5292621d97834592c983a341e6e8759a8437dd208448a0226459c91e7b273f8c
    gitImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init
      tag: v0.30.0
      digest: sha256:3637bac1e233696a3671155c77de9ed8e02cacbec454d314125a5f1f458effa3
    entrypointImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint
      tag: v0.30.0
      digest: sha256:34ee7658bb8a657584e1ada8e84121758cc5d067c1f0740873d614d07423886f
    nopImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop
      tag: v0.30.0
      digest: sha256:89cb4d5572372c7ade6b20b59bf35dc9dcd5e4cde2fa77f14888d4f7059cd767
    imagedigestExporterImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter
      tag: v0.30.0
      digest: sha256:2a6dec9e6d66b2198d9bc3bcf1f03a662e4eb274b66563c5d499e9f29dadcc10
    prImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init
      tag: v0.30.0
      digest: sha256:d321d1888a203be9fab57aa528bcf378da6984778c38f015c0a9287fc489602f
    gsutilImage:
      repository: gcr.io/google.com/cloudsdktool/cloud-sdk
      tag:
      digest: sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f
    shellImage:
      repository: ghcr.io/distroless/busybox
      tag:
      digest: sha256:cfdc553400d41b47fd231b028403469811fcdbc0e69d66ea8030c5a0b5fbac2b
    shellImageWin:
      repository: mcr.microsoft.com/powershell:nanoserver
      tag:
      digest: sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
  type: ClusterIP
featureFlags:
  disableAffinityAssistant: "false"
  disableCredsInit: "false"
  disableHomeEnvOverwrite: "true"
  disableWorkingDirectoryOverwrite: "true"
  enableApiFields: stable
  enableCustomTasks: "false"
  enableTektonOciBundles: "false"
  requireGitSshSecretKnownHosts: "false"
  runningInEnvironmentWithInjectedSidecars: "true"
  scopeWhenExpressionsToTask: "false"
kubernetesClusterDomain: cluster.local
pipelinesInfo:
  version: v0.30.0
webhook:
  ports:
    - name: http-metrics
      port: 9090
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
    - name: https-webhook
      port: 443
      targetPort: 8443
    - name: probes
      port: 8080
      targetPort: 0
  replicas: 1
  type: ClusterIP
  webhook:
    image:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
      tag: v0.30.0
      digest: sha256:b93422365865e7b6fbe96e92cac7494626257165021fa36f71fae22bdfbd3e6e
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
