{{- if .Values.global.Contour.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-gateway
  namespace: openfunction
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: kubectl
        image: bitnami/kubectl:1.22
        command:
        - kubectl
        - delete
        - gateway
        - openfunction
        - --ignore-not-found=true
      restartPolicy: Never
      serviceAccountName: {{ include "openfunction.fullname" . }}-controller-manager
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-ns
  namespace: openfunction
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: kubectl
        image: bitnami/kubectl:1.22
        command:
        - kubectl
        - delete
        - ns
        - {{ .Values.contour.namespaceOverride }}
        - --wait=false
        - --ignore-not-found=true
      restartPolicy: Never
      serviceAccountName: ns-edit
{{- end }}