apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-edit
  namespace: openfunction
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded