apiVersion: v1
kind: Service
metadata:
  name: domainmapping-webhook
  labels:
    app.kubernetes.io/component: domain-mapping
    role: domainmapping-webhook
    serving.knative.dev/release: v1.3.2
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.domainmappingWebhook.type }}
  selector:
    role: domainmapping-webhook
  {{- include "knative-serving.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.domainmappingWebhook.ports | toYaml | nindent 2 -}}