apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: activator-pdb
  labels:
    app.kubernetes.io/component: activator
    serving.knative.dev/release: v1.3.2
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: activator