apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image
metadata:
  name: queue-proxy
  labels:
    app.kubernetes.io/component: queue-proxy
    serving.knative.dev/release: v1.3.2
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  {{- with .Values.configDeployment.queueSidecarImage }}
  image: {{ .repository }}:{{ .tag }}
  {{- end }}