apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-controller
  labels:
    app: tekton-pipelines-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: v0.37.2
    pipeline.tekton.dev/release: v0.37.2
    version: v0.37.2
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.type }}
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.controller.ports | toYaml | nindent 2 -}}