apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    app: controller
    app.kubernetes.io/component: controller
    serving.knative.dev/release: v1.3.2
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.type }}
  selector:
    app: controller
  {{- include "knative-serving.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.controller.ports | toYaml | nindent 2 -}}