apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  labels:
    app.kubernetes.io/component: controller
    serving.knative.dev/release: v1.3.2
  {{- include "knative-serving.labels" . | nindent 4 }}