apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-serving-podspecable-binding
  labels:
    duck.knative.dev/podspecable: "true"
    serving.knative.dev/release: v1.3.2
  {{- include "knative-serving.labels" . | nindent 4 }}
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - configurations
  - services
  verbs:
  - list
  - watch
  - patch