apiVersion: v1
kind: Service
metadata:
  name: default-domain-service
  labels:
    app: default-domain
    app.kubernetes.io/component: default-domain-job
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.3.2
    serving.knative.dev/release: v1.3.2
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.defaultDomain.type }}
  selector:
    app: default-domain
  {{- include "knative-serving.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.defaultDomain.ports | toYaml | nindent 2 -}}