{{- if .Values.global.Contour.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-contour
  labels:
    app.kubernetes.io/component: net-contour
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.3.0
    networking.knative.dev/ingress-provider: contour
    serving.knative.dev/release: v1.3.0
  {{- include "knative-serving.labels" . | nindent 4 }}
data:
  visibility: |
    ExternalIP:
      class: contour
      service: projectcontour/contour-envoy
    ClusterLocal:
      class: contour
      service: projectcontour/contour-envoy
  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # timeout-policy-idle sets TimeoutPolicy.Idle in contour HTTPProxy spec
    timeout-policy-idle: "infinity"

    # timeout-policy-response sets TimeoutPolicy.Response in contour HTTPProxy spec
    timeout-policy-response: "infinity"

    # If auto-TLS is disabled fallback to the following certificate
    #
    # An operator is required to setup a TLSCertificateDelegation
    # for this secret to be used
    default-tls-secret: "some-namespace/some-secret"

    # visibility contains the configuration for how to expose services
    # of assorted visibilities.  Each entry is keyed by the visibility
    # and contains two keys:
    #  1. the "class" value to pass to the Contour class annotations,
    #  2. the namespace/name of the Contour Envoy service.
    visibility: |
      ExternalIP:
        class: contour-external
        service: contour-external/envoy
      ClusterLocal:
        class: contour-internal
        service: contour-internal/envoy
{{- end }}