apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  labels:
    app.kubernetes.io/component: networking
    serving.knative.dev/release: v1.3.2
    {{- include "knative-serving.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: ddc3250f
data:
  {{- if .Values.global.Contour.enabled }}
  ingress-class: "contour.ingress.networking.knative.dev"
  {{- end }}
  _example: |
  {{- .Files.Get "files/network.example" | nindent 4 }}