apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  labels:
    app.kubernetes.io/component: observability
    serving.knative.dev/release: v1.3.2
  {{- include "knative-serving.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: fed4756e
data:
  _example: |
  {{- .Files.Get "files/network.example" | nindent 4 }}